import "./globals.css";
import { ThemeContextProvider } from "./context/ThemeContext";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
        <Navbar />
        {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
